### ISSUE TITLE
After installing, ava no longer works stand-alone

### ISSUE THREAD

**Issue by rickgn** [dnlup/vue-cli-plugin-unit-ava#3] opened 2019-03-25 16:06 UTC
Installed your plugin.  I'm not sure how installing a plugin could make this happen but now I cannot run ava directly from command line.  It seems that there are some assumptions in paths and modules that are causing breaking changes if I have my own setup file.  My feedback is that while doing everything automatically is nice for first-time installation, installing into an existing project should take into account that developers might already have a setup they are happy with, but want to also use vue-cli plugin.   Maybe an install option or more documentation would be helpful. 

> ava
simple.test.js:1
  (function (exports, require, module, __filename, __dirname) { import test from 'ava';
SyntaxError: Unexpected identifier  'test'

in package.json
```
    "require": [
      "./test/helpers/setup.js"
    ],
  ```
is replaced with 
```
    "require": "./node_modules/@dnlup/vue-cli-plugin-unit-ava/setup.js",
```

If it's helpful to understand my test setup, here is the setup.js file:
```
require('browser-env')();
const hooks = require('require-extension-hooks');
const Vue = require('vue');
Vue.config.productionTip = false;
hooks('vue').plugin('vue').push();
hooks(['vue', 'js']).exclude(({filename}) => filename.match(/\/node_modules\//)).plugin('babel').push();
```

**Comment by dnlup** [comment] 2019-03-25 16:32
@rickgn Thanks for the feedback. Detailed documentation will arrive. I will also look into how this plugin could be used better in an existing project. In the meantime I should maybe convey better the philosophy behind this package.
Compilation is done with `webpack`, so the setup file that uses node `require hooks` as suggested in the ava recipes) should not be used (it's not needed). I left its config value in `package.json` to allow modification if needed (if you check the default file you will see that is not using node `require hooks` and its purpose is different). Why this? Because doing so you can use all the webpack loaders you would normally use during app development without writing a setup file that would have to mimic the same setup you would use with webpack. 
The drawback is (as you pointed out) that calling ava directly does not work anymore in this configuration, you should call instead
```
npm run test:unit -- <your file>
```
Hope this helps a little for now.

**Comment by dnlup** [comment] 2019-03-26 15:56
@rickgn Following one of your suggestion I tried to add more documentation, the goal is to explain what the plugin does under the hood. I will also try to mimic a setup like yours and see what is the exact cause of your problem.

**Comment by rickgn** [comment] 2019-04-03 13:29
I have to admit I'm new to Ava.  We really like working with Ava but the challenge has been using it in both node es6 mode + in Vue at the same time.  For example we have some components which are headless such as a services broker / API abstraction.  The es6 module made that part of testing very easy. But then with es6 activated in ava require, we had trouble making Vue components compile and test.  I'm hoping vue-cli-plugin-unit-ava can solve these issues.

**Comment by dnlup** [comment] 2019-04-08 10:25
@rickgn So you have to run both node and vue tests in the same project? Can you share a project sample or make a small repo where you can reproduce the issue?

**Comment by rickgn** [comment] 2019-04-10 23:12
@dnlup It's not that I need to run Node and browser in the same project. I do however desire to independently test service components not mounted in the UI.  To give you an example, we are doing large file parsing and other CPU intensive operations in 100's of thousands of records, all client side. These run in web workers. It's obviously quite difficult to test a web worker with a mounted component. Therefore we essentially need to run these headless components/modules as if they are Node and test accordingly.   I don't have a problem with having two separate test scripts for these suites; one for headless and one for shallow mounted.  I think my issue is getting Webpack, Babel, Ava, etc. to all work in both configs.  

So it seems by your question you are wondering why I'm trying to do this rather than split into two projects. I'll have to think about that.  However, it would be nice to have environment / script specific parameter that allows me to control which setup to use.  Otherwise I would need to run independent tests on multiple projects + integration test, etc. Sounds like a lot of work.  :-/

**Comment by dnlup** [comment] 2019-04-12 07:58
@rickgn 
I see. I get your problem now and how the plugin default configuration is messing up with your project.
This can be solved in more than one way, but I think the cleanest would be:

#### multiple configurations
One configuration to run `ava` directly, one to run the plugin.
Since `ava` can use only one config file (`package.json` or `ava.config.js`) per project (by project
I mean a folder with a `package.json` file) I would move all the plugin options on a dedicated section in `package.json` or in `vue.config.js` (see https://cli.vuejs.org/config/#pluginoptions) and
manually load them as cli options when launching `ava` internally in the plugin. This way you can keep
your old setup and run test scripts switching configuration.



In the meantime, if you want to run those service components tests today, you could try 2 things:
* run `ava` overriding all the plugin options via cli options
* run the plugin command but use something like [this](https://github.com/developit/jsdom-worker) to
  test the service workers. Since the plugin uses webpack and jsdom, service workers are not supported
  out of the box.


I am going to work on handling configuration differently.

**Comment by dnlup** [comment] 2019-04-30 10:21
Hi @rickgn, first I would like to apologize for giving you inaccurate advice before. It is not possible to override all ava cli options directly from the command line.
Secondly, I have put together a possible solution to this problem in this [PR](https://github.com/dnlup/vue-cli-plugin-unit-ava/pull/9). Basically the plugin configuration is moved in the `vue.config.js` file and I am porting internally in the plugin the ava cli code to launch it with my custom options.

Could you test if this is starting to work for you? Here's what you should do:


```bash
$ cd <your project>
```

install the plugin branch
```bash
$ npm i -D dnlup/vue-cli-plugin-unit-ava#options
```

invoke the plugin generator
```bash
$ vue invoke @dnlup/unit-ava
```

launch the plugin tests
```bash
$ npm run test:unit
```

launch your tests
```bash
$ npm test or <your command>
```

If you wish to configure the ava used in the plugin you should use the `vue.config.js` file:

```js
module.exports = {
  pluginOptions: {
    '@dnlup/vue-cli-plugin-unit-ava': {
      // Your config, beware of not override the options
      // showed in the README for now.
    }
  }
}
```

**Comment by dnlup** [comment] 2019-05-21 12:03
@rickgn I just released a new version. 
I am not using webpack anymore for compiling test files but I am using the approach suggested in [ava recipes](https://github.com/avajs/ava/blob/master/docs/recipes/vue.md). So now `ava` is working stand-alone. Also, if you need multiple configurations for different test cases you could use `ava.config.js` file to export the needed config object. Let me know if this solve your issue or what could be improved.

**Comment by dnlup** [comment] 2019-05-28 07:32
@rickgn I think this issue is solved in the latest version and it is easier to configure `ava` to work as you want in case this setup doesn't work out of the box. I am going to close this, feel free to re-open it if in case I am wrong.
Thanks for your feedback.

**Closed by dnlup** 2019-05-28 07:32 UTC
